---
- hosts: localhost
  tasks:
    - name: Set sane defaults for QLColorCode QuickLook plugin
      osx_defaults:
        domain: org.n8gray.QLColorCode
        key: extraHLFlags
        type: string
        value: '-l -W --kw-case=none'
        state: present
    - name: "Safari: Enable Debug menu"
      osx_defaults:
        domain: com.apple.Safari
        key: IncludeInternalDebugMenu
        type: integer
        value: 1
